### ISSUE TITLE
What does the example do?

### ISSUE THREAD

**Issue by gdalle** [exanauts/ColPack.jl#10]
The file https://github.com/michel2323/ColPack.jl/blob/master/examples/coloring.jl doesn't seem to be used anywhere, and it tries to read a matrix from a file without downloading it first

**Comment by michel2323** [comment]
That's indeed messy. ColPack has an mtx reader.

**Comment by gdalle** [comment]
I removed it in #11

**Comment by amontoison** [comment]
We should keep it in a section of the documentation.
It is always useful to try the algorithm directly on mtx files.

**Comment by gdalle** [comment]
Okay but this script doesn't run anyway since the downloading part is not written. Feel free to add something that uses e.g. https://github.com/JuliaLinearAlgebra/MatrixDepot.jl

**Comment by amontoison** [comment]
Ok I was aware of that.
It's a good idea to remove the file in that case.

**Comment by gdalle** [comment]
I want to add more docs anyway once I figure out how the package works (e.g. with #12). I can always add an example where a matrix is downloaded from the sparse matrix connection, stored in `mtx` and then retrieved. But I want it to actually run in the docs, not just be some displayed code

**Comment by amontoison** [comment]
The package SuiteSparseMatrixCollection.jl can download and install the mtx files for you as an artifact.
